---

- name: install sysstat
  ansible.builtin.yum:
    name: sysstat

- name: get installed version
  ansible.builtin.yum:
    list: sysstat
  register: sysstat_installed_version_getter

- name: set installed version fact
  ansible.builtin.set_fact:
    sysstat_installed_version: >-
      {{ sysstat_installed_version_getter.results.0.version }}

- name: configure sysstat
  ansible.builtin.template:
    src: 'sysstat-conf-{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.j2'
    dest: '/etc/sysconfig/sysstat'
    owner: root
    group: root
    mode: 0644

- name: configure sysstat cron
  ansible.builtin.template:
    src: 'sysstat-cron.j2'
    dest: '/etc/cron.d/sysstat'
    owner: root
    group: root
    mode: 0600

- name: set sysstat service status
  ansible.builtin.service:
    name: sysstat
    enabled: '{{ sysstat_sar_service }}'
  tags:
    - service

...
