---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  # ansible-core requires a minimum of Python2 version 2.7 or Python3 version 3.5. Current version: 2.6.6
  - name: centos-6
    image: geerlingguy/docker-centos6-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: centos-7
    image: geerlingguy/docker-centos7-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: centos-8
    image: geerlingguy/docker-centos8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: rocky-8
    image: geerlingguy/docker-rockylinux8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

provisioner:
  name: ansible
  inventory:
    host_vars:
      archlinux:
        ansible_user: ansible

verifier:
  name: ansible

...
